name: scanpy_spatial
channels:
 - conda-forge
 - bioconda
 - defaults
 - anaconda
dependencies:
 - python=3.8.5
 - pip=20.2.2
 - pytorch=1.4.0
 - pandas=1.1.0
 - numpy=1.21.2
 - numba=0.52.0 
 - torchvision
 - cudatoolkit=10.2 
 - scipy=1.5.2
 - matplotlib-base=3.3.1
 - seaborn=0.11.1
 - jupyterlab=2.2.6
 - nb_conda=2.2.1
 - leidenalg
 - igraph
 - pip:
   - scanpy>=1.6.0
   - comet_ml
   - scikit-learn
   - tangram-sc==0.4.0
   - squidpy==1.1.1
   - scanorama
   - umap-learn





